@echo off
REM -------------------------------------------------------
REM  Cmd-script autogenerated by im4java
REM  at Thu Jan 23 23:24:19 MST 2014
REM -------------------------------------------------------

set PATH=C:\Program Files\ImageMagick-6.8.8-Q16;%PATH%

convert ^
  "C:\Users\Edward\Documents\Programming\TIResizeMaven\images\base" ^
  -resize "1000x1000" "C:\Users\Edward\Documents\Programming\TIResizeMaven\images\1000"

