// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.turbointernational.metadata.domain.part;

import com.turbointernational.metadata.domain.part.BearingHousing;
import javax.persistence.Entity;

privileged aspect BearingHousing_Roo_Jpa_Entity {
    
    declare @type: BearingHousing: @Entity;
    
}
