// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.turbointernational.metadata.domain.part;

import com.turbointernational.metadata.domain.part.JournalBearing;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JournalBearing_Roo_Configurable {
    
    declare @type: JournalBearing: @Configurable;
    
}
