// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.turbointernational.metadata.domain;

import com.turbointernational.metadata.domain.AttributeType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AttributeType_Roo_Configurable {
    
    declare @type: AttributeType: @Configurable;
    
}
