// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.turbointernational.metadata.domain;

import com.turbointernational.metadata.domain.GasketType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GasketType_Roo_Configurable {
    
    declare @type: GasketType: @Configurable;
    
}
