<?php if ($this->getCurrencyCount() > 1): ?>
    <label for="custom-currency-selector" style="font-weight: bold;"><?php echo $this->__('Currency') ?></label>
    <select onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector"
        style="margin-right: 5px;">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"
                <?php if ($_code == $this->getCurrentCurrencyCode()): ?>
                    selected="SELECTED"
                <?php endif; ?>>
                <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
    </select>
<?php endif; ?>