// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ti.metadata.domain.other;

import org.springframework.beans.factory.annotation.Configurable;
import ti.metadata.domain.other.Manfr;

privileged aspect Manfr_Roo_Configurable {
    
    declare @type: Manfr: @Configurable;
    
}
