// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ti.metadata.domain.security;

import org.springframework.beans.factory.annotation.Configurable;
import ti.metadata.domain.security.UserGroupPK;

privileged aspect UserGroupPK_Roo_Configurable {
    
    declare @type: UserGroupPK: @Configurable;
    
}
