// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ti.metadata.domain.part;

import org.springframework.beans.factory.annotation.Configurable;
import ti.metadata.domain.part.StandardBearingSpacer;

privileged aspect StandardBearingSpacer_Roo_Configurable {
    
    declare @type: StandardBearingSpacer: @Configurable;
    
}
